"""Add analysis_log to frames

Revision ID: 6183a74baa27
Revises: 840ed5b44af5
Create Date: 2025-12-29 12:07:31.196752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6183a74baa27'
down_revision = '840ed5b44af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frames', sa.Column('analysis_log', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frames', 'analysis_log')
    # ### end Alembic commands ###
