"""Add is_verified to scene_attributes

Revision ID: 840ed5b44af5
Revises: 20260801000000_movie_metadata_payloads
Create Date: 2025-12-29 11:41:55.909398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840ed5b44af5'
down_revision = '20260801000000_movie_metadata_payloads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_attributes', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_attributes', 'is_verified')
    # ### end Alembic commands ###
